spring:
    datasource:
        password: password
        url: jdbc:postgresql://localhost:5432/db
        username: user
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
