version: '2'

services:
  server:
    image: 'ticketing:latest'
    build:
      context: .
    container_name: server
    depends_on:
      - db
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres'
      - 'SPRING_DATASOURCE_USERNAME=user'
      - 'SPRING_DATASOURCE_PASSWORD=password'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=create'
    ports:
      - "8080:8080"
  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '5432:5432'
